### PR TITLE
[ci] Make the call-ci-script job part of the build-and-deploy job

### PR DESCRIPTION
**Pull request by gkaracha**

### CODE REVIEW

**Comment by gkaracha** [comment]
@silky I made the call to the `ci.yml` job a sequential step in the `doc.yml` workflow, and also reverted 3e02f5570c5a5c074e5a1051d86a208251c21b44; haddock seems to always take a long time and recompile a lot, so having it run for every push and pr is not very efficient.

**Comment by silky** [comment]
@gkaracha definitely don't want it to run for every PR; but certainly every push is reasonable, i think.

**Comment by silky** [comment]
i guess i think we should just simply have two caches; one for the build that buidls on PRs, and one for the docs that builds on merge to main

so maybe we can refactor it that way? that saves calling out to the other script.

**Comment by silky** [comment]
i think this is now resolved by #34 and #29 and #32

**Comment by gkaracha** [comment]
Looks like it @silky; nice! :D

**Pull request closed without merging**
