### PR TITLE
Use an MIT license instead

### PR DESCRIPTION
**Pull request by gkaracha**
Licensing belongs to Tweag and we are not at liberty to pick a license of our choosing.

### CODE REVIEW

**Review by aspiwack — APPROVED** [review]

**Comment by marcosh** [comment]
merge blocked by https://github.com/mstksg/setup-stack/issues/16

**Comment by silky** [comment]
Interesting development.

As a maintainer of, and contributor too, this project, I will explicitly state that I do not support this license change; though I understand the reason.

I think therefore I'll step down from the maintainership of this codebase and continue any further work over here: https://github.com/silky/servant-oauth2.

I would say that it would be nice if Tweag, as a significant contributor and supporter of open-source, would take a firm, inspiring, and leading stance on the usage of open-source code for positive purposes; and if you find that the Hippocratic license _isn't_ the best way to do this, I'd be curious to hear what thoughts you _do_ have to start to make this necessary change and address the (rapidly failing) status quo of leaving "politics" out of code.

**Comment by purcell** [comment]
I think it would have helped here if there were a clear default licence policy for Tweag's open source contributions — @aspiwack, I'd encourage you to establish that.

I'm open to tuning that policy for maximum community and societal benefit, but it's a complex issue. (For instance, the Hippocratic Licence is "non-free" in the assessment of the idealists at FSF.)

Concretely, I'm fairly confident that Tweag would not seek to enforce the restrictions of that licence — both due to the aims of the licence being non-goals of the company, and the lack of legal precedent. It's also unclear whether the disclaimers of liability or other protections established by the licence for the copyright owner are robust. In the meantime, the MIT licence is at least a known and safe quantity from a risk perspective.

That's a _very_ boring and corporate response, I know, but @silky: thank you for illuminating this topic, and I wish you the best with the experiment of offering future enhancements under that more progressive licence.

**Comment by purcell** [comment]
FWIW, since you asked about effective strategies for realising such societal change, my personal view is that open source software should be public domain and very liberally licensed, regardless of purpose — I mostly consider OSS code to be written publication of ethically-neutral methods and knowledge. However, we can skew those publications of code to be most applicable to beneficial domains, or present them in the context of such applications.

**Pull request merged**
